name: fe-nc-news

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd fe-nc-news
          git pull origin master
          docker-compose down
          docker-compose pull
          docker-compose up --build -d
          sudo systemctl restart nginx
